### ISSUE TITLE
Error with 'phage_contig_annotator download_db': configparser.NoSectionError: No section: 'databases'

### ISSUE THREAD

**Issue by ZongzhiWu** [Yasas1994/phage_contig_annotator#4]
Hi Yasas, many thanks for your tools.
When I tried to download database for phage_contig_annotator, I came across an error as below:

**Command:**
`phage_contig_annotator download_db`

**Output log:**
```
06-Aug-24 10:52:12 : INFO : phage_contig_annotator is a simple pipeline to add PHROG annotations to phage contigs
06-Aug-24 10:52:12 : INFO : downloading PHROG database
1627800.0MB [00:19, 414056.27MB/s]06-Aug-24 11:00:28 : INFO : database downloaded and extracted to /home/wuzongzhi2022phd/miniconda3/envs/phage_contig_annot/lib/python3.10/site-packages/databases
1627800.0MB [01:22, 19666.07MB/s]
Traceback (most recent call last):
  File "/home/wuzongzhi2022phd/miniconda3/envs/phage_contig_annot/bin/phage_contig_annotator", line 8, in <module>
    sys.exit(main())
  File "/home/wuzongzhi2022phd/miniconda3/envs/phage_contig_annot/lib/python3.10/site-packages/cli.py", line 182, in main
    config.set('databases','dbroot',args.path)
  File "/home/wuzongzhi2022phd/miniconda3/envs/phage_contig_annot/lib/python3.10/configparser.py", line 1206, in set
    super().set(section, option, value)
  File "/home/wuzongzhi2022phd/miniconda3/envs/phage_contig_annot/lib/python3.10/configparser.py", line 904, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'databases'
```

**Comment by Yasas1994** [comment]
Hi Zongzhi,
Thanks for reporting this bug.  I have just pushed a fix to the repo :)
Please let me know if everything works well now

**Comment by ZongzhiWu** [comment]
Thanks a lot. `phage_contig_annotator download_db` works well now.
